disabled_rules:
  - todo
  - trailing_whitespace
opt_in_rules:
  - empty_count
  - closure_spacing
  - contains_over_first_not_nil
  - first_where
  - force_unwrapping
  - implicitly_unwrapped_optional
  - redundant_nil_coalescing
  - unused_import
  - vertical_whitespace_closing_braces
included:
  - FoodMap
  - FoodMapTests
excluded:
  - .build
  - DerivedData
  - Tooling
line_length:
  warning: 140
  error: 200
  ignores_comments: true
type_body_length:
  warning: 350
  error: 500
file_length:
  warning: 500
  error: 800
function_body_length:
  warning: 80
  error: 140
identifier_name:
  min_length: 2
  excluded:
    - id
    - x
    - y
    - to
reporter: "xcode"
